# Generated by Django 6.1.1 on 2026-10-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Refrigerator', 'Refrigerator'), ('Air Conditioner', 'Air Conditioner'), ('Washing Machine', 'Washing Machine'), ('Television', 'Television'), ('Microwave', 'Microwave'), ('Water Heater', 'Water Heater'), ('Laptop', 'Laptop'), ('Other', 'Other')], default='Other', max_length=50)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model_number', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(default='Home', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Service Due', 'Service Due'), ('Maintenance', 'Maintenance'), ('Out of Order', 'Out of Order')], default='Active', max_length=50)),
                ('image_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('Purchase Bill', 'Purchase Bill'), ('Invoice', 'Invoice'), ('Warranty Card', 'Warranty Card'), ('Insurance Document', 'Insurance Document'), ('Certificate', 'Certificate'), ('Service Document', 'Service Document'), ('Other', 'Other')], default='Other', max_length=50)),
                ('file_url', models.TextField(blank=True, default='')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ocr_extracted_text', models.TextField(blank=True, default='')),
                ('appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('due_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('Upcoming Service', 'Upcoming Service'), ('Overdue Service', 'Overdue Service'), ('Warranty Expiry', 'Warranty Expiry'), ('Document Expiry', 'Document Expiry'), ('Service Request Update', 'Service Request Update')], default='Upcoming Service', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled')], default='Completed', max_length=50)),
                ('provider', models.CharField(blank=True, default='Authorized Service Center', max_length=150)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_histories', to='api.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('issue_description', models.TextField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Reported', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=50)),
                ('assigned_technician', models.CharField(blank=True, default='Pending Assignment', max_length=100)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='api.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=150)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField()),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Every 3 months', 'Every 3 months'), ('Every 6 months', 'Every 6 months'), ('Yearly', 'Yearly'), ('Custom', 'Custom')], default='Every 6 months', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='api.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='Manufacturer', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('warranty_type', models.CharField(default='Standard Manufacturer Warranty', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expiring Soon', 'Expiring Soon'), ('Expired', 'Expired')], default='Active', max_length=50)),
                ('terms', models.TextField(blank=True, default='')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='api.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
